### ISSUE TITLE
Unable to See the Full Screen of the Controlled Computer When Using Remote Control

### ISSUE THREAD

**Issue by YujioNako** [bitbound/ControlR#8]
### Issue Checklist

- [ √ ] Includes repro steps that result in the bug presenting
- [ √ ] Searched for existing issues
- [ √ ] Filled out the below sections
- [ √ ] Filled out the
- [ √ ] Does not relate to hosting (server configuration, reverse proxy, Cloudflare, etc.)
  - The public server is hosted behind Cloudflare, behind Caddy reverse proxy on the server, and using the same image as everyone else. (i.e. The app works.)
  - Connection issues are likely due to something in between the browser and the ControlR backend app, not the app itself.
  - Please go to the Discussions section for help with hosting setups.

### Describe the bug

When I use remote control, I cannot see the full screen of the controlled computer from the control side. I can only see the top left corner of the other party's screen.

### To Reproduce

In the `Home-Device` page, when connecting to any controlled device using remote control.

### Client Info

Browser:  Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
Agent Version:  0.11.16.0
Agent OS: Windows 11

### Host Info (if self-hosting)

Host OS:  CentOS 8
Docker image tag: translucency/controlr:latest

Other relevant info: /

### Screenshots

![image](https://github.com/user-attachments/assets/efe0a4e4-de69-46c5-975b-34a6afd0883f)

**Comment by bitbound** [comment]
Unable to reproduce.  Included testing on a 4K display with resolution scaling.

https://github.com/user-attachments/assets/42efd6cc-3b89-47ae-8209-909cb1681aba
